artifacts_root : artifacts

data_ingestion:
     root_dir: data_ingestion
     source_url: https://github.com/shivamsaini7227/DataWeNeed/raw/main/archive.zip
     local_file: /Users/shivamsaini/chicken-disease/artifacts/dataingestion/archive.zip
     unzip_dir: artifacts/dataingestion

base_model:
     root_dir: artifacts/base_model
     base_model_path: artifacts/base_model/model.h5
     updated_base_model_path: artifacts/base_model/updated_model.h5

prepare_callbacks:
     root_dir: artifacts/prepare_callbacks
     tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
     checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.keras
